
Initialization took 3.613520860671997 seconds
Traceback (most recent call last):
  File "/Users/volodimir/Downloads/Bachelor/CrossValidation/training.py", line 144, in <module>
    train()
  File "/Users/volodimir/Downloads/Bachelor/CrossValidation/training.py", line 64, in train
    val_loss, val_precision, val_recall, val_f1, val_balanced_accuracy, val_conf_matrix) = train_epoch(network,
                                                                                           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/Downloads/Bachelor/CrossValidation/utils.py", line 270, in train_epoch
    for images, labels in train_loader:
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/Users/volodimir/Downloads/Bachelor/CrossValidation/utils.py", line 80, in __getitem__
    image = read_image(frame_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torchvision/io/image.py", line 258, in read_image
    data = read_file(path)
           ^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torchvision/io/image.py", line 52, in read_file
    data = torch.ops.image.read_file(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: [Errno 2] No such file or directory: '/Volumes/LaCie/Macbook/Bachelor/CrossValidation/cropped/video_frames/012_image_66351195251695.mp4/frame_70.png'