2024-03-17 20:50:03,972 INFO    StreamThr :7782 [internal.py:wandb_internal():86] W&B internal server running at pid: 7782, started at: 2024-03-17 20:50:03.972075
2024-03-17 20:50:03,974 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: status
2024-03-17 20:50:03,987 INFO    WriterThread:7782 [datastore.py:open_for_write():87] open: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/run-hamlrfj3.wandb
2024-03-17 20:50:03,987 DEBUG   SenderThread:7782 [sender.py:send():382] send: header
2024-03-17 20:50:04,004 DEBUG   SenderThread:7782 [sender.py:send():382] send: run
2024-03-17 20:50:04,446 INFO    SenderThread:7782 [dir_watcher.py:__init__():211] watching files in: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files
2024-03-17 20:50:04,447 INFO    SenderThread:7782 [sender.py:_start_run_threads():1136] run started: hamlrfj3 with start time 1710705003.973818
2024-03-17 20:50:04,465 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: check_version
2024-03-17 20:50:04,465 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: check_version
2024-03-17 20:50:04,594 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: run_start
2024-03-17 20:50:04,603 DEBUG   HandlerThread:7782 [system_info.py:__init__():27] System info init
2024-03-17 20:50:04,603 DEBUG   HandlerThread:7782 [system_info.py:__init__():42] System info init done
2024-03-17 20:50:04,604 INFO    HandlerThread:7782 [system_monitor.py:start():194] Starting system monitor
2024-03-17 20:50:04,604 INFO    SystemMonitor:7782 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-17 20:50:04,604 INFO    HandlerThread:7782 [system_monitor.py:probe():214] Collecting system info
2024-03-17 20:50:04,605 DEBUG   HandlerThread:7782 [system_info.py:probe():151] Probing system
2024-03-17 20:50:04,605 INFO    SystemMonitor:7782 [interfaces.py:start():190] Started cpu monitoring
2024-03-17 20:50:04,605 INFO    SystemMonitor:7782 [interfaces.py:start():190] Started disk monitoring
2024-03-17 20:50:04,609 INFO    SystemMonitor:7782 [interfaces.py:start():190] Started gpuapple monitoring
2024-03-17 20:50:04,611 INFO    SystemMonitor:7782 [interfaces.py:start():190] Started memory monitoring
2024-03-17 20:50:04,612 INFO    SystemMonitor:7782 [interfaces.py:start():190] Started network monitoring
2024-03-17 20:50:04,616 DEBUG   HandlerThread:7782 [system_info.py:_probe_git():136] Probing git
2024-03-17 20:50:04,632 DEBUG   HandlerThread:7782 [system_info.py:_probe_git():144] Probing git done
2024-03-17 20:50:04,632 DEBUG   HandlerThread:7782 [system_info.py:probe():199] Probing system done
2024-03-17 20:50:04,632 DEBUG   HandlerThread:7782 [system_monitor.py:probe():223] {'os': 'macOS-13.3.1-arm64-arm-64bit', 'python': '3.11.0', 'heartbeatAt': '2024-03-17T19:50:04.605398', 'startedAt': '2024-03-17T19:50:03.952971', 'docker': None, 'cuda': None, 'args': ('--batch_size=64', '--fold=fold_0', '--transform=random_crop'), 'state': 'running', 'program': '/Users/volodimir/Downloads/Bachelor/CrossValidation/training.py', 'codePathLocal': 'training.py', 'codePath': 'CrossValidation/training.py', 'git': {'remote': 'https://github.com/Asthera/Bachelor.git', 'commit': '759222e2800d90531a940fd485b868f1380a0bb3'}, 'email': 'h', 'root': '/Users/volodimir/Downloads/Bachelor', 'host': 'MacBook-Air-Volodimir.local', 'username': 'volodimir', 'executable': '/Users/volodimir/anaconda3/envs/Global/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 189.87229537963867}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-03-17 20:50:04,633 INFO    HandlerThread:7782 [system_monitor.py:probe():224] Finished collecting system info
2024-03-17 20:50:04,633 INFO    HandlerThread:7782 [system_monitor.py:probe():227] Publishing system info
2024-03-17 20:50:04,633 DEBUG   HandlerThread:7782 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-03-17 20:50:05,448 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/conda-environment.yaml
2024-03-17 20:50:06,680 DEBUG   HandlerThread:7782 [system_info.py:_save_conda():220] Saving conda packages done
2024-03-17 20:50:06,680 INFO    HandlerThread:7782 [system_monitor.py:probe():229] Finished publishing system info
2024-03-17 20:50:06,682 DEBUG   SenderThread:7782 [sender.py:send():382] send: files
2024-03-17 20:50:06,682 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-03-17 20:50:06,685 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: python_packages
2024-03-17 20:50:06,685 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: python_packages
2024-03-17 20:50:06,685 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: stop_status
2024-03-17 20:50:06,686 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: stop_status
2024-03-17 20:50:06,686 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 20:50:07,056 DEBUG   SenderThread:7782 [sender.py:send():382] send: telemetry
2024-03-17 20:50:07,056 DEBUG   SenderThread:7782 [sender.py:send():382] send: telemetry
2024-03-17 20:50:07,056 DEBUG   SenderThread:7782 [sender.py:send():382] send: run
2024-03-17 20:50:07,223 INFO    SenderThread:7782 [sender.py:send_run():1010] updated run: hamlrfj3
2024-03-17 20:50:07,457 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/config.yaml
2024-03-17 20:50:07,457 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/conda-environment.yaml
2024-03-17 20:50:07,457 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:07,458 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-metadata.json
2024-03-17 20:50:07,458 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/requirements.txt
2024-03-17 20:50:07,586 INFO    wandb-upload_0:7782 [upload_job.py:push():131] Uploaded file /var/folders/r9/fn8812cd1czdjdytwc97q1h80000gn/T/tmpfr2mmet1wandb/40x4tu84-wandb-metadata.json
2024-03-17 20:50:09,468 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:09,656 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: status_report
2024-03-17 20:50:11,478 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:12,156 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:50:12,157 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 20:50:12,157 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 20:50:12,158 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 20:50:12,480 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-summary.json
2024-03-17 20:50:13,485 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:14,759 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: status_report
2024-03-17 20:50:15,497 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:16,682 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:50:16,682 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 20:50:16,682 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 20:50:16,682 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 20:50:17,506 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:17,506 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-summary.json
2024-03-17 20:50:19,522 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:20,097 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: status_report
2024-03-17 20:50:21,091 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:50:21,091 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 20:50:21,091 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 20:50:21,092 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 20:50:21,542 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:21,542 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-summary.json
2024-03-17 20:50:21,690 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: stop_status
2024-03-17 20:50:21,690 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 20:50:21,691 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: stop_status
2024-03-17 20:50:23,564 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 20:50:25,403 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:50:26,725 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 20:50:29,709 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:50:31,768 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 20:50:34,039 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:50:36,701 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 20:50:37,779 WARNING FileStreamThread:7782 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x1024774d0>>, timeout=180.0), args: ('https://api.wandb.ai/files/daswoldemar/bachelor-test/hamlrfj3/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 33, 'content': ['2024-03-17T19:50:19.264173 Memory allocated:  321304064\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.23946428298950195\n', '2024-03-17T19:50:19.264173 Memory allocated:  321306112\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.23946619033813477\n', '2024-03-17T19:50:19.264173 Memory allocated:  321452544\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.2395007610321045\n']}}, 'dropped': 0}}
2024-03-17 20:50:38,542 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:57:47,295 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 20:57:48,638 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:57:52,338 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 20:57:52,938 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:57:56,841 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 20:57:57,251 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:58:01,562 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:58:02,393 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 20:58:05,865 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 20:58:07,440 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 20:58:09,754 DEBUG   SystemMonitor:7782 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-17 20:58:11,852 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 20:58:17,495 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 20:58:22,509 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 20:58:26,852 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 20:58:32,575 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:00:04,274 INFO    SenderThread:7782 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x1185c25d0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1185c25d0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1185c25d0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2024-03-17 21:00:04,309 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:00:08,438 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 21:00:11,621 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: log_artifact
2024-03-17 21:00:12,356 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table/vaL_confusion_matrix_12_186341c056d1081947ca.table.json
2024-03-17 21:00:12,357 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media
2024-03-17 21:00:12,357 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table
2024-03-17 21:00:17,381 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:00:22,413 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:00:23,440 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 21:00:26,656 WARNING FileStreamThread:7782 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/daswoldemar/bachelor-test/hamlrfj3/file_stream (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x118576c50>, 'Connection to api.wandb.ai timed out. (connect timeout=180.0)')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x1024774d0>>, timeout=180.0), args: ('https://api.wandb.ai/files/daswoldemar/bachelor-test/hamlrfj3/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 33, 'content': ['2024-03-17T19:50:19.264173 Memory allocated:  321304064\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.23946428298950195\n', '2024-03-17T19:50:19.264173 Memory allocated:  321306112\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.23946619033813477\n', '2024-03-17T19:50:19.264173 Memory allocated:  321452544\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.2395007610321045\n']}}, 'dropped': 0}}
2024-03-17 21:00:28,452 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:00:33,492 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:00:38,451 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 21:00:43,532 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:15:59,269 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:16:00,723 WARNING FileStreamThread:7782 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/daswoldemar/bachelor-test/hamlrfj3/file_stream (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1185b8250>, 'Connection to api.wandb.ai timed out. (connect timeout=180.0)')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x1024774d0>>, timeout=180.0), args: ('https://api.wandb.ai/files/daswoldemar/bachelor-test/hamlrfj3/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 33, 'content': ['2024-03-17T19:50:19.264173 Memory allocated:  321304064\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.23946428298950195\n', '2024-03-17T19:50:19.264173 Memory allocated:  321306112\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.23946619033813477\n', '2024-03-17T19:50:19.264173 Memory allocated:  321452544\n', '2024-03-17T19:50:19.264173 Memory allocated:  0.2395007610321045\n']}}, 'dropped': 0}}
2024-03-17 21:16:01,865 INFO    SenderThread:7782 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x118776990>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x118776990>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x118776990>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2024-03-17 21:16:03,142 INFO    wandb-upload_0:7782 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x118776810>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x118776810>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x118776810>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2024-03-17 21:17:49,364 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 21:17:51,252 ERROR   wandb-upload_0:7782 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/daswoldemar/bachelor-test/hamlrfj3/media/table/vaL_confusion_matrix_12_186341c056d1081947ca.table.json?Expires=1710793070&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Uh75HRXzpK092xH%2BQKibN%2FtzXMroNMbT4rD4tn3H0gp0rbOh9h1jabIUFNYK9pjHCWflc60KqWw3M0icNNwNcreUBIv0OuKzDCLu%2B9bJEN0CZYda1oqaQlwoFlwaT9WrEw5RbDLZqFvyb2ccws0KUT%2BS5UZiTWYjFojI06xne7wsPHlhO8XInnGwDeNfys5anRH7zTJEdc%2Btg6nM5LOQbN5R6fBJ4jZLfXaCclV57z1%2F83ORyDYXKFj3%2F6okHSiov%2FMyBsAJuibxGKpUMFeN0LHK5P81qL%2FyC0uDfJE6lGYlDDcbGuOgCYwvS7bchymsfD2cdWWROqHCGCdRILxvKQ%3D%3D: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-03-17 21:17:51,252 ERROR   wandb-upload_0:7782 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '298'}
2024-03-17 21:17:51,252 ERROR   wandb-upload_0:7782 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-17 21:17:51,558 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: log_artifact
2024-03-17 21:17:51,570 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 21:17:51,627 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table/train_confusion_matrix_12_e86a130799961daa6c7a.table.json
2024-03-17 21:17:51,628 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table
2024-03-17 21:17:52,106 INFO    wandb-upload_1:7782 [upload_job.py:push():131] Uploaded file /var/folders/r9/fn8812cd1czdjdytwc97q1h80000gn/T/tmpfr2mmet1wandb/cnh5xhdg-media/table/train_confusion_matrix_12_e86a130799961daa6c7a.table.json
2024-03-17 21:17:52,574 INFO    wandb-upload_0:7782 [upload_job.py:push():131] Uploaded file /var/folders/r9/fn8812cd1czdjdytwc97q1h80000gn/T/tmpfr2mmet1wandb/jxbkg9de-media/table/vaL_confusion_matrix_12_186341c056d1081947ca.table.json
2024-03-17 21:17:53,767 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: log_artifact
2024-03-17 21:17:53,781 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: partial_history
2024-03-17 21:17:54,454 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table/confusion_matrix_table_13_c14b05bf2d5fb8af76e9.table.json
2024-03-17 21:17:54,455 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table
2024-03-17 21:17:54,790 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-17 21:17:54,874 INFO    wandb-upload_1:7782 [upload_job.py:push():131] Uploaded file /var/folders/r9/fn8812cd1czdjdytwc97q1h80000gn/T/tmpfr2mmet1wandb/r3f19pfp-media/table/confusion_matrix_table_13_c14b05bf2d5fb8af76e9.table.json
2024-03-17 21:17:59,804 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:18:04,828 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: keepalive
2024-03-17 21:18:05,169 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: status_report
2024-03-17 21:18:05,365 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,366 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,367 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,369 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,369 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,370 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,371 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,371 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,372 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,373 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,373 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,373 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,375 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,375 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,376 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,377 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,377 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,378 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,379 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,379 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,379 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,380 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,380 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,381 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,382 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,382 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,382 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:05,382 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:05,382 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:05,383 DEBUG   SenderThread:7782 [sender.py:send():382] send: telemetry
2024-03-17 21:18:05,383 DEBUG   SenderThread:7782 [sender.py:send():382] send: stats
2024-03-17 21:18:05,383 DEBUG   SenderThread:7782 [sender.py:send():382] send: stats
2024-03-17 21:18:05,383 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: log_artifact
2024-03-17 21:18:05,490 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/config.yaml
2024-03-17 21:18:05,490 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-summary.json
2024-03-17 21:18:06,098 INFO    SenderThread:7782 [sender.py:send_request_log_artifact():1470] logged artifact run-hamlrfj3-vaL_confusion_matrix - {'id': 'QXJ0aWZhY3Q6NzYwMzEyNjQ1', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE0OTc4ODIzOA==', 'latestArtifact': None}}
2024-03-17 21:18:06,098 DEBUG   SenderThread:7782 [sender.py:send():382] send: files
2024-03-17 21:18:06,098 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file media/table/vaL_confusion_matrix_12_186341c056d1081947ca.table.json with policy now
2024-03-17 21:18:06,098 DEBUG   SenderThread:7782 [sender.py:send():382] send: stats
2024-03-17 21:18:06,098 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: log_artifact
2024-03-17 21:18:06,450 INFO    SenderThread:7782 [sender.py:send_request_log_artifact():1470] logged artifact run-hamlrfj3-train_confusion_matrix - {'id': 'QXJ0aWZhY3Q6NzYwMzEyNjU0', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE0OTc4ODI0MA==', 'latestArtifact': None}}
2024-03-17 21:18:06,450 DEBUG   SenderThread:7782 [sender.py:send():382] send: files
2024-03-17 21:18:06,451 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file media/table/train_confusion_matrix_12_e86a130799961daa6c7a.table.json with policy now
2024-03-17 21:18:06,452 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:06,452 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:06,453 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:06,454 DEBUG   SenderThread:7782 [sender.py:send():382] send: config
2024-03-17 21:18:06,454 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: log_artifact
2024-03-17 21:18:06,496 INFO    Thread-12 :7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-summary.json
2024-03-17 21:18:06,651 INFO    wandb-upload_1:7782 [upload_job.py:push():131] Uploaded file /var/folders/r9/fn8812cd1czdjdytwc97q1h80000gn/T/tmpfr2mmet1wandb/doufnwna-media/table/vaL_confusion_matrix_12_186341c056d1081947ca.table.json
2024-03-17 21:18:06,855 INFO    SenderThread:7782 [sender.py:send_request_log_artifact():1470] logged artifact run-hamlrfj3-confusion_matrix_table - {'id': 'QXJ0aWZhY3Q6NzYwMzEyNjU5', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE0OTc4ODI0MQ==', 'latestArtifact': None}}
2024-03-17 21:18:06,856 DEBUG   SenderThread:7782 [sender.py:send():382] send: files
2024-03-17 21:18:06,856 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file media/table/confusion_matrix_table_13_c14b05bf2d5fb8af76e9.table.json with policy now
2024-03-17 21:18:06,857 DEBUG   SenderThread:7782 [sender.py:send():382] send: history
2024-03-17 21:18:06,857 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: summary_record
2024-03-17 21:18:06,858 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:06,858 INFO    wandb-upload_0:7782 [upload_job.py:push():89] Uploaded file /Users/volodimir/Library/Application Support/wandb/artifacts/staging/tmp1igc8jfh
2024-03-17 21:18:06,858 DEBUG   SenderThread:7782 [sender.py:send():382] send: exit
2024-03-17 21:18:06,859 INFO    SenderThread:7782 [sender.py:send_exit():589] handling exit code: 0
2024-03-17 21:18:06,859 INFO    SenderThread:7782 [sender.py:send_exit():591] handling runtime: 1669
2024-03-17 21:18:06,864 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:06,864 INFO    SenderThread:7782 [sender.py:send_exit():597] send defer
2024-03-17 21:18:06,864 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: poll_exit
2024-03-17 21:18:06,865 DEBUG   SenderThread:7782 [sender.py:send():382] send: stats
2024-03-17 21:18:06,865 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:06,866 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 0
2024-03-17 21:18:06,866 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:06,866 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 0
2024-03-17 21:18:06,867 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 1
2024-03-17 21:18:06,867 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:06,867 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 1
2024-03-17 21:18:06,867 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:06,867 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 1
2024-03-17 21:18:06,867 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 2
2024-03-17 21:18:06,868 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:06,868 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 2
2024-03-17 21:18:06,868 INFO    HandlerThread:7782 [system_monitor.py:finish():203] Stopping system monitor
2024-03-17 21:18:06,868 DEBUG   SystemMonitor:7782 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-17 21:18:06,868 DEBUG   SystemMonitor:7782 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-17 21:18:06,868 INFO    HandlerThread:7782 [interfaces.py:finish():202] Joined cpu monitor
2024-03-17 21:18:06,870 INFO    HandlerThread:7782 [interfaces.py:finish():202] Joined disk monitor
2024-03-17 21:18:06,870 INFO    HandlerThread:7782 [interfaces.py:finish():202] Joined gpuapple monitor
2024-03-17 21:18:06,871 INFO    HandlerThread:7782 [interfaces.py:finish():202] Joined memory monitor
2024-03-17 21:18:06,871 INFO    HandlerThread:7782 [interfaces.py:finish():202] Joined network monitor
2024-03-17 21:18:06,872 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:06,872 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 2
2024-03-17 21:18:06,872 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 3
2024-03-17 21:18:06,872 DEBUG   SenderThread:7782 [sender.py:send():382] send: stats
2024-03-17 21:18:06,872 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:06,873 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 3
2024-03-17 21:18:06,873 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:06,873 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 3
2024-03-17 21:18:06,873 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 4
2024-03-17 21:18:06,873 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:06,873 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 4
2024-03-17 21:18:06,873 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:06,873 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 4
2024-03-17 21:18:06,873 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 5
2024-03-17 21:18:06,873 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:06,873 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 5
2024-03-17 21:18:06,874 DEBUG   SenderThread:7782 [sender.py:send():382] send: summary
2024-03-17 21:18:06,874 INFO    SenderThread:7782 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-17 21:18:06,874 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:06,874 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 5
2024-03-17 21:18:06,874 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 6
2024-03-17 21:18:06,874 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:06,874 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 6
2024-03-17 21:18:06,874 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:06,874 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 6
2024-03-17 21:18:06,876 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: status_report
2024-03-17 21:18:07,045 INFO    wandb-upload_3:7782 [upload_job.py:push():131] Uploaded file /var/folders/r9/fn8812cd1czdjdytwc97q1h80000gn/T/tmpfr2mmet1wandb/ifphzskq-media/table/train_confusion_matrix_12_e86a130799961daa6c7a.table.json
2024-03-17 21:18:07,097 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 7
2024-03-17 21:18:07,097 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:07,097 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 7
2024-03-17 21:18:07,098 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:07,098 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 7
2024-03-17 21:18:07,262 INFO    wandb-upload_2:7782 [upload_job.py:push():89] Uploaded file /Users/volodimir/Library/Application Support/wandb/artifacts/staging/tmpf8abc9s6
2024-03-17 21:18:07,477 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 8
2024-03-17 21:18:07,478 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:07,478 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 8
2024-03-17 21:18:07,478 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:07,478 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 8
2024-03-17 21:18:07,478 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 9
2024-03-17 21:18:07,478 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:07,478 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 9
2024-03-17 21:18:07,479 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:07,479 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 9
2024-03-17 21:18:07,479 INFO    SenderThread:7782 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-17 21:18:07,500 INFO    SenderThread:7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 21:18:07,500 INFO    SenderThread:7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/config.yaml
2024-03-17 21:18:07,500 INFO    SenderThread:7782 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-summary.json
2024-03-17 21:18:07,501 INFO    SenderThread:7782 [dir_watcher.py:finish():388] scan: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files
2024-03-17 21:18:07,501 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/requirements.txt requirements.txt
2024-03-17 21:18:07,501 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log output.log
2024-03-17 21:18:07,502 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/config.yaml config.yaml
2024-03-17 21:18:07,502 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-summary.json wandb-summary.json
2024-03-17 21:18:07,502 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/conda-environment.yaml conda-environment.yaml
2024-03-17 21:18:07,502 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-metadata.json wandb-metadata.json
2024-03-17 21:18:07,502 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table/train_confusion_matrix_12_e86a130799961daa6c7a.table.json media/table/train_confusion_matrix_12_e86a130799961daa6c7a.table.json
2024-03-17 21:18:07,503 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table/vaL_confusion_matrix_12_186341c056d1081947ca.table.json media/table/vaL_confusion_matrix_12_186341c056d1081947ca.table.json
2024-03-17 21:18:07,503 INFO    SenderThread:7782 [dir_watcher.py:finish():402] scan save: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/media/table/confusion_matrix_table_13_c14b05bf2d5fb8af76e9.table.json media/table/confusion_matrix_table_13_c14b05bf2d5fb8af76e9.table.json
2024-03-17 21:18:07,503 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 10
2024-03-17 21:18:07,503 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:07,503 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 10
2024-03-17 21:18:07,503 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:07,503 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 10
2024-03-17 21:18:07,503 INFO    SenderThread:7782 [file_pusher.py:finish():172] shutting down file pusher
2024-03-17 21:18:07,623 INFO    wandb-upload_1:7782 [upload_job.py:push():89] Uploaded file /Users/volodimir/Library/Application Support/wandb/artifacts/staging/tmpjvytlsfs
2024-03-17 21:18:07,839 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-17 21:18:07,840 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: poll_exit
2024-03-17 21:18:08,465 INFO    wandb-upload_0:7782 [upload_job.py:push():131] Uploaded file /var/folders/r9/fn8812cd1czdjdytwc97q1h80000gn/T/tmpfr2mmet1wandb/ciu7s8i9-media/table/confusion_matrix_table_13_c14b05bf2d5fb8af76e9.table.json
2024-03-17 21:18:08,846 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-17 21:18:08,846 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: poll_exit
2024-03-17 21:18:09,409 INFO    wandb-upload_4:7782 [upload_job.py:push():131] Uploaded file /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/output.log
2024-03-17 21:18:09,416 INFO    wandb-upload_0:7782 [upload_job.py:push():131] Uploaded file /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/conda-environment.yaml
2024-03-17 21:18:09,451 INFO    wandb-upload_1:7782 [upload_job.py:push():131] Uploaded file /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/config.yaml
2024-03-17 21:18:09,469 INFO    wandb-upload_3:7782 [upload_job.py:push():131] Uploaded file /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/wandb-summary.json
2024-03-17 21:18:09,553 INFO    wandb-upload_2:7782 [upload_job.py:push():131] Uploaded file /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/files/requirements.txt
2024-03-17 21:18:09,852 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-17 21:18:09,852 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: poll_exit
2024-03-17 21:18:10,117 INFO    Thread-11 (_thread_body):7782 [sender.py:transition_state():617] send defer: 11
2024-03-17 21:18:10,119 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:10,119 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 11
2024-03-17 21:18:10,121 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:10,121 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 11
2024-03-17 21:18:10,121 INFO    SenderThread:7782 [file_pusher.py:join():178] waiting for file pusher
2024-03-17 21:18:10,126 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 12
2024-03-17 21:18:10,129 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:10,129 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 12
2024-03-17 21:18:10,129 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:10,129 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 12
2024-03-17 21:18:10,129 INFO    SenderThread:7782 [file_stream.py:finish():595] file stream finish called
2024-03-17 21:18:10,858 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-17 21:18:10,943 INFO    SenderThread:7782 [file_stream.py:finish():599] file stream finish is done
2024-03-17 21:18:10,943 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 13
2024-03-17 21:18:10,943 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: poll_exit
2024-03-17 21:18:10,944 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:10,944 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 13
2024-03-17 21:18:10,944 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:10,945 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 13
2024-03-17 21:18:10,945 INFO    SenderThread:7782 [sender.py:transition_state():617] send defer: 14
2024-03-17 21:18:10,945 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: defer
2024-03-17 21:18:10,946 DEBUG   SenderThread:7782 [sender.py:send():382] send: final
2024-03-17 21:18:10,946 INFO    HandlerThread:7782 [handler.py:handle_request_defer():172] handle defer: 14
2024-03-17 21:18:10,946 DEBUG   SenderThread:7782 [sender.py:send():382] send: footer
2024-03-17 21:18:10,946 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: defer
2024-03-17 21:18:10,946 INFO    SenderThread:7782 [sender.py:send_request_defer():613] handle sender defer: 14
2024-03-17 21:18:10,947 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-17 21:18:10,948 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: poll_exit
2024-03-17 21:18:10,949 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-17 21:18:10,949 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: server_info
2024-03-17 21:18:10,950 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: poll_exit
2024-03-17 21:18:10,950 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: get_summary
2024-03-17 21:18:10,951 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: server_info
2024-03-17 21:18:10,955 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: sampled_history
2024-03-17 21:18:10,957 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-17 21:18:10,958 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: job_info
2024-03-17 21:18:11,133 DEBUG   SenderThread:7782 [sender.py:send_request():409] send_request: job_info
2024-03-17 21:18:11,133 INFO    MainThread:7782 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-17 21:18:11,135 INFO    MainThread:7782 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-17 21:18:11,136 INFO    MainThread:7782 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-17 21:18:11,140 DEBUG   HandlerThread:7782 [handler.py:handle_request():146] handle_request: shutdown
2024-03-17 21:18:11,140 INFO    HandlerThread:7782 [handler.py:finish():869] shutting down handler
2024-03-17 21:18:11,963 INFO    WriterThread:7782 [datastore.py:close():296] close: /Users/volodimir/Downloads/Bachelor/CrossValidation/wandb/run-20240317_205003-hamlrfj3/run-hamlrfj3.wandb
2024-03-17 21:18:12,138 INFO    SenderThread:7782 [sender.py:finish():1572] shutting down sender
2024-03-17 21:18:12,139 INFO    SenderThread:7782 [file_pusher.py:finish():172] shutting down file pusher
2024-03-17 21:18:12,139 INFO    SenderThread:7782 [file_pusher.py:join():178] waiting for file pusher
