Traceback (most recent call last):
  File "/Users/volodimir/Desktop/Bachelor/training_sweep.py", line 62, in <module>
    })
  File "/Users/volodimir/Desktop/Bachelor/training_sweep.py", line 48, in train
    test_loss, test_accuracy, true_labels, predicted_labels, precision, recall, f1 = test_model(network, test_loader, criterion, device)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4)