
Initialization took 4.718213081359863 seconds
Traceback (most recent call last):
  File "/Users/volodimir/Downloads/Bachelor/CrossValidation/training.py", line 144, in <module>
    train()
  File "/Users/volodimir/Downloads/Bachelor/CrossValidation/training.py", line 64, in train
    val_loss, val_precision, val_recall, val_f1, val_balanced_accuracy, val_conf_matrix) = train_epoch(network,
                                                                                           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/Downloads/Bachelor/CrossValidation/utils.py", line 273, in train_epoch
    for images, labels in train_loader:
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/Users/volodimir/Downloads/Bachelor/CrossValidation/utils.py", line 82, in __getitem__
    if len(self.resolution) == 2 and self.resolution[0] == self.resolution[1]:
       ^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()